spring:
  profiles:
    active: nature

server:
  port: 8080

sim:
  width: 20
  height: 20
  threads: 4
  tickMs: 100
  broadcast-interval: 5
  broadcast-rate-ms: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha

---
spring:
  config:
    activate:
      on-profile: nature
sim:
  width: 30
  height: 30

---
spring:
  config:
    activate:
      on-profile: simcity
sim:
  width: 15
  height: 15
  tickMs: 200
