wolf.weight=50
wolf.maxPerCell=30
wolf.speed=3
wolf.foodForSaturation=8
wolf.lifespan=10000
wolf.prey=horse:10,deer:15,rabbit:60,mouse:80,goat:60,sheep:70,wild_boar:15,buffalo:10,duck:40

fox.weight=8
fox.maxPerCell=30
fox.speed=2
fox.foodForSaturation=2
fox.lifespan=10000
fox.prey=rabbit:70,mouse:90,duck:50,caterpillar:95

rabbit.weight=2
rabbit.maxPerCell=150
rabbit.speed=2
rabbit.foodForSaturation=0.45
rabbit.lifespan=10000

duck.weight=1
duck.maxPerCell=200
duck.speed=4
duck.foodForSaturation=0.15
duck.lifespan=10000
duck.prey=caterpillar:90

caterpillar.weight=0.01
caterpillar.maxPerCell=1000
caterpillar.speed=0
caterpillar.foodForSaturation=0
caterpillar.lifespan=2147483647
